name: ESLint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      - name: Install Dependencies
        run: npm ci; npm run build --if-present

      - name: Run ESLint
        run: npm run lint
